name = "Flows"
uuid = "b7844722-a0ec-11e9-22bc-51d568b73702"
authors = ["Kai Xu <xukai921110@gmail.com>"]
version = "0.1.0"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[extras]
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[targets]
test = ["Distributions", "Bijectors", "Flux"]
